### ISSUE TITLE
Incorrect parsing at fromString

### ISSUE THREAD

**Issue by decafbad** [cmditch/elm-bigint#1]
Output of   `fromString "--2"`  is `Just (Neg (Magnitude [-2]))`

Then, this happens:

`Maybe.map (mul (fromInt -3)) (fromString "--2") |> Maybe.map toString`
`Just "-19999994"`

**Comment by cmditch** [comment]
Good catch.

I'm inclined to treat "--2" as invalid. Can you provide any reasons for why "--" might be a useful pattern?

Thanks

**Comment by decafbad** [comment]
I was working on a Fraction library based on this one. My own bug raised this problem. All kinds of malformed string should return Nothing anyways.

**Comment by cmditch** [comment]
Finally fixed 👍 
https://github.com/cmditch/elm-bigint/commit/e2350f4be81d3ecec81632d9d352aad28b218d92
